version: "3.4"

services:
  laravel-app:
    build:
      context: '.'
      #args:
      #uid: ${UID}
    container_name: laravel-app
    environment:
      XDEBUG_CLIENT_HOST: 127.0.1.1
      XDEBUG_CLIENT_PORT: 9003
      PHP_IDE_CONFIG: serverName=vsc
    #  - APACHE_RUN_USER=#${UID}
    #  - APACHE_RUN_GROUP=#${UID}
    volumes:
      - ./html:/var/www/html
    ports:
      - 8000:80

  db:
    image: mysql
    container_name: mysql-db
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=docker_laravel
      - MYSQL_PASSWORD=dockerLaravel
      - MYSQL_ROOT_PASSWORD=dockerLaravel8
    ports:
      - 3306:3306
